import type { UserRole } from "@/types";

const adminPermissions: string[] = [
  "deployments:read",
  "deployments:write",
  "deployments:delete",
  "certificates:read",
  "certificates:write",
  "certificates:delete",
  "networks:read",
  "networks:write",
  "networks:delete",
  "security:read",
  "security:write",
  "backups:read",
  "backups:write",
  "backups:delete",
  "users:read",
  "users:write",
  "users:delete",
  "apikeys:read",
  "apikeys:write",
  "apikeys:delete",
  "settings:read",
  "settings:write",
  "audit:read",
  "containers:read",
  "containers:write",
  "containers:delete",
  "images:read",
  "images:write",
  "images:delete",
  "volumes:read",
  "volumes:write",
  "volumes:delete",
  "databases:read",
  "databases:write",
  "databases:delete",
  "infrastructure:read",
  "infrastructure:write",
  "scheduler:read",
  "scheduler:write",
  "scheduler:delete",
  "system:read",
  "system:write",
  "dns:read",
  "dns:write",
  "registries:read",
  "registries:write",
  "registries:delete",
  "templates:read",
  "templates:write",
  "traffic:read",
  "traffic:write",
];

const operatorPermissions: string[] = [
  "deployments:read",
  "deployments:write",
  "certificates:read",
  "certificates:write",
  "networks:read",
  "security:read",
  "backups:read",
  "backups:write",
  "apikeys:read",
  "apikeys:write",
  "apikeys:delete",
  "settings:read",
  "containers:read",
  "containers:write",
  "images:read",
  "images:write",
  "volumes:read",
  "volumes:write",
  "databases:read",
  "databases:write",
  "infrastructure:read",
  "infrastructure:write",
  "scheduler:read",
  "scheduler:write",
  "system:read",
  "system:write",
  "dns:read",
  "dns:write",
  "registries:read",
  "registries:write",
  "templates:read",
  "traffic:read",
];

const viewerPermissions: string[] = [
  "deployments:read",
  "certificates:read",
  "networks:read",
  "security:read",
  "backups:read",
  "apikeys:read",
  "settings:read",
  "containers:read",
  "images:read",
  "volumes:read",
  "databases:read",
  "infrastructure:read",
  "scheduler:read",
  "system:read",
  "dns:read",
  "registries:read",
  "templates:read",
  "traffic:read",
];

export function getRolePermissions(role: UserRole): string[] {
  switch (role) {
    case "admin":
      return [...adminPermissions];
    case "operator":
      return [...operatorPermissions];
    case "viewer":
      return [...viewerPermissions];
    default:
      return [];
  }
}
